### ISSUE TITLE
News tab with broken nginx

### ISSUE THREAD

**Issue by akissz** [aarnt/octopkg#11]
Why does the news tab say the site permanently moved. It only shows a broken nginx site link.
![newstaberror](https://user-images.githubusercontent.com/23090286/92476567-caf1db80-f1a4-11ea-96b9-173fb2fc81d2.png)

**Comment by aarnt** [comment]
@akissz 

You are probably using an older version. Version 0.3.1 can retrieve all 4 BSD compatible news.
