### ISSUE TITLE
Use of red for a non-error that is misinterpreted as an error

### ISSUE THREAD

**Issue by grahamperrin** [aarnt/octopkg#13]
From <https://forums.freebsd.org/threads/82993/>: 

![image](https://user-images.githubusercontent.com/192271/142765966-b86701c4-4330-4252-89e9-cc5188d38a5e.png)

* installing the port [security/linux-c7-libgpg-error](https://www.freshports.org/security/linux-c7-libgpg-error/) of [libgpg-error](https://www.gnupg.org/software/libgpg-error/)

– it's assumed that use of red is triggered by the word _error_.

**Comment by aarnt** [comment]
Fixed upstream.

**Comment by grahamperrin** [comment]
Thanks, excuse my ignorance/confusion, does upstream = Octopi?

**Comment by aarnt** [comment]
Upstream is the development code of Octopkg. It means I've just changed the development code.
