### ISSUE TITLE
Consider not using -f -y (nonquestioning force) by default

### ISSUE THREAD

**Issue by grahamperrin** [aarnt/octopkg#14]
An example dialogue: 

![image](https://user-images.githubusercontent.com/192271/143316858-5a7c5397-9170-4093-8df5-14ccf83c4969.png)

Can there be a preference to _not_ force things by default? 

In some cases, removals – for which there's no forewarning – might be troublesome. 

<https://github.com/aarnt/octopkg/issues/3#issuecomment-183935274> it's possible to cancel an in-progress transaction, but avoidance will be preferable. 

Thanks

**Comment by aarnt** [comment]
Now, upstream no longer uses "pkg remove" with -f option.
