### ISSUE TITLE
Release tarball

### ISSUE THREAD

**Issue by nunotexbsd** [aarnt/octopkg#17]
Could upstream have/produce a release tarball?

https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

Thanks

**Comment by aarnt** [comment]
@nunotexbsd 
You mean this: https://github.com/aarnt/octopkg/releases/tag/v0.3.3

**Comment by nunotexbsd** [comment]
@aarnt 
Please take a look at https://github.com/jordansissel/xdotool/releases/tag/v3.20211022.1 and you see 3 Assets files: auto-generated .tar.gz and .zip and a release tarball https://github.com/jordansissel/xdotool/releases/download/v3.20211022.1/xdotool-3.20211022.1.tar.gz

**Comment by aarnt** [comment]
@nunotexbsd 
Updated the release tarball.

**Comment by nunotexbsd** [comment]
@aarnt

Thanks!
https://cgit.freebsd.org/ports/commit/?id=011bb37b45cad2494a3b8424535c77c268a826d7
