### ISSUE TITLE
Feature request: ability to clear search

### ISSUE THREAD

**Issue by trombonehero** [aarnt/octopkg#2]
First of all, thanks for octopkg: it's going to make it much easier for me to promote FreeBSD within my university!

Now, for the actual feature request. If I:
1. enter a search term in the search bar,
2. click the "X" in the search bar to clear the search term and
3. press Enter,

I would expect the GUI to show me the complete list of packages like it did before I entered a search term. Instead, it warns me that "Search string must have at least 2 characters." So, it seems that there is no way to get back from a set of search results to the Big List of Packages...

**Comment by aarnt** [comment]
You just need to click "Install a new package (Ctrl+I) button again.
