### ISSUE TITLE
Freezes after applying updates

### ISSUE THREAD

**Issue by nunotexbsd** [aarnt/octopkg#20]
From PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276024

This issue started since upgraded to latest patch of FreeBSD 13.2 but persist in FreeBSD 14.0.
I believe it may be related with pkg tool itself, maybe there was a change and it's giving unexpected results back to octopkg.

I can't reproduce it on my local 15-CURRENT as it do all operations normally.

Is there a way to investigate this problem?

**Comment by aarnt** [comment]
@nunotexbsd Hi, is it still happening? I've never had this kind of issue here in my Free 13 and 14 computers.

**Comment by nunotexbsd** [comment]
@aarnt 

Hello, I will close this PR as I completely forgot to do it when dealing with this issue.
There is no complaints for more than 5 months and I was never able to reproduced it.

Thanks very much
