### ISSUE TITLE
Feature request: ability to cancel in-progress transaction

### ISSUE THREAD

**Issue by trombonehero** [aarnt/octopkg#3]
At the command line, I can cancel a long transaction (e.g., installing `texlive-full`) with Control-C. It would be nice if octopkg provided similar functionality from the GUI. Perhaps the transaction will be cancelled if I close octopkg (or maybe it won't?), but I'd like a big, friendly cancel button. :)

**Comment by aarnt** [comment]
Now you're able to cancel the current transaction using "Ctrl+C".
