### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by ShalokShalom** [aarnt/octopkg#5]
Is this project in coma?

**Comment by aarnt** [comment]
http://www.zen-buddhism.net/

"Keep your back straight. Let your ego and your unconscious mind melt away, merge with the universe."

**Comment by ShalokShalom** [comment]
So yes.

**Comment by ghost** [comment]
On Fri, 27 Jan 2017 05:29:39 -0800
Alexandre Arnt <notifications@github.com> wrote:

> http://www.zen-buddhism.net/
> 
> "Keep your back straight. Let your ego and your unconscious mind melt away,
> merge with the universe."
> 
> 

LoL!

**Comment by aarnt** [comment]
No, it is not.
